### ISSUE TITLE
Do not find all files

### ISSUE THREAD

**Issue by moueza** [winzou/mooc-symfony#4]
Hello
On github website Entity is here
But when  `git clone https://github.com/winzou/mooc-symfony.git`, 
`ls src/OC/PlatformBundle/
Controller  DependencyInjection  OCPlatformBundle.php  Resources  Tests` : Entity is not there.
Have I missed something?

**Comment by Ilshidur** [comment]
The master branch does not contain the code you're looking for. You need to use the proper branch.
This MOOC is split in chapters with an 'iteration-X' branch corresponding to each chapter.

Just do :

```shell
git clone https://github.com/winzou/mooc-symfony.git mooc
cd $_
git checkout iteration-X # Replace X
```

You can find the corresponding branch in the "Résumé" section like [here](https://openclassrooms.com/courses/developpez-votre-site-web-avec-le-framework-symfony/tp-consolidation-de-notre-code#r-3623334).

**Comment by moueza** [comment]
Ah OK.
Thank you
